name: Pull Request validation

on: [pull_request]


jobs:
  credchain-contracts-ci:
    name: Run credchain-contracts validation
    uses: ./.github/workflows/credchain-contracts-ci.yaml

  credchain-frontend-ci:
    name: Run credchain-frontend validation
    uses: ./.github/workflows/credchain-frontend-ci.yaml

